variable "bucket_name" {}
variable "iam_policy_name" {}
variable "iam_policy_description" {}
variable "iam_role_name" {}
variable "iam_role_description" {}
variable "repo_name" {}
variable "channel_secret_name" {}
variable "channel_secret_description" {}
variable "channel_secret_value" {}
variable "channel_token_name" {}
variable "channel_token_description" {}
variable "channel_token_value" {}
