version = 0.1
### Dev環境 ###
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda-dev"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
s3_bucket = "aws-sam-cli-managed-bucket"
s3_prefix = "lambda-dev"

### Prod環境 ###
[prod]

[prod.deploy]
[prod.deploy.parameters]
stack_name = "lambda-prod"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
s3_bucket = "aws-sam-cli-managed-bucket"
s3_prefix = "lambda-prod"