version = 0.1
### Dev環境 ###
[dev.deploy]
[dev.deploy.parameters]
stack_name = "lambda-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
s3_bucket = "sam-food-search"
s3_prefix = "dev"

### Prd環境 ###
[prd]

[prd.deploy]
[prd.deploy.parameters]
stack_name = "lambda-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
s3_bucket = "sam-food-search"
s3_prefix = "prd"